name: _
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

workspace:  
  - my_app
  - packages/package_core
  - packages/feature_one

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  
  cupertino_icons: ^1.0.8
  go_router: ^14.8.1
  dio: ^5.8.0+1
  riverpod_annotation: ^2.6.1
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  retrofit: ^4.4.2
  flutter_native_splash: ^2.4.5
  flutter_launcher_icons: ^0.14.3
  riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.5
  freezed: ^3.0.3
  json_serializable: ^6.9.4
  mocktail: ^1.0.4
  pretty_dio_logger: ^1.4.0
  retrofit_generator: ^9.1.9
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
  build_runner: ^2.4.15
