name: package_core
description: "A new Flutter package project."
version: 0.0.1
homepage: https://example.com

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

resolution: workspace 

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter