name: package_core
description: "A new Flutter package project."
version: 0.0.1
homepage: https://example.com

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

resolution: workspace 

dev_dependencies:
  riverpod_generator: ^2.6.5
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  retrofit_generator: ^9.1.9