name: package_core
description: "A new Flutter package project."
version: 0.0.1
homepage: https://example.com

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  riverpod_annotation: ^2.6.1
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  retrofit: ^4.4.2
  riverpod: ^2.6.1

dev_dependencies:
  build_runner: ^2.4.15
  riverpod_generator: ^2.6.5
  freezed: ^3.0.3
  json_serializable: ^6.9.4
  retrofit_generator: ^9.1.9
  custom_lint: ^0.7.5